services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:delegated
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d:ro
    depends_on:
      - app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      LANG: C.UTF-8
      TZ: Europe/Moscow
      MYSQL_INIT_COMMAND: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/test.sql:/docker-entrypoint-initdb.d/test.sql:ro

volumes:
  db_data:
